# --- !Ups

create table "todo_items" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "description" varchar not null,
    "is_done" int not null
);

# --- !Downs
drop table "todo_items" if exists;